channels:
    - conda-forge

dependencies:
    - pip
    - python>=3.6
    - numpy
    - scipy
    - matplotlib
    - pandas
    - pytables
    - pillow
    - scikit-image
    - requests
    - scrapy
    - jupyter
    - jupyterlab
    - notebook
    - ipywidgets
    - tqdm
    - joblib
    - nodejs
    - pytest
    - flake8
    - pylint
    - autopep8
    # Tensorflow dependencies
    - protobuf
    - absl-py
    - gast
    - astor
    - termcolor
    - h5py
    - wrapt
    - keras-preprocessing
    - keras-applications
    - google-pasta
    # Tensorboard dependencies
    - werkzeug
    - markdown
    - grpcio
    # Tensorflow dataset dependencies
    - psutil
    - promise
    - dill
    # Keras tuner deps
    - terminaltables
    - tabulate
    #- pip:
    # Install TF deps not available on Conda.
    #- pip install --no-deps -U tensorflow-datasets tensorflow_metadata tensorboard tensorflow-estimator tensorflow_hub tensorflowjs
    # Install TF (from nightly or not).
    #- pip install --no-deps -U tensorflow-gpu==2.0.0-beta1
    #- pip install --no-deps -U https://github.com/keras-team/keras-tuner/archive/2722577dfe85b7285b1944e1984566a09dd643c2.zip
